### ISSUE TITLE
Default voulme

### ISSUE THREAD

**Issue by GerSant** [Martvvliet/homebridge-denon-heos#19]
Can put a config parameter to setup a default volume, maybe a global param and individual input param?

Thanks

**Comment by Martvvliet** [comment]
Do you mean that when you turn on the receiver, it also sets the volume to this default value? Or a separate switch for a default volume? I know you can set a default startup volume level in the Denon settings. At least In my x-1400h it is possible.

**Comment by GerSant** [comment]
Yes, a default startup volume level in the global config and an override specific default volume for each input, what do you think? :)

**Comment by Martvvliet** [comment]
This might be possible to add. But I thought something like this is already possible through the shortcuts app. Not sure if this works as expected. Will do some tests :)

**Comment by GerSant** [comment]
I understand, but remember, shortcuts has only one iCloud account scope, if do you have more than one iCloud in you home (means family) all the devices need to be configured with the respective shortcut

**Comment by Martvvliet** [comment]
Yeah that's true indeed. I didn't think about that Will check if I can integrate it in the current plugin. Thank you for your feedback

**Comment by GerSant** [comment]
Thanks to you for this excellent plugin

**Comment by Martvvliet** [comment]
@GerSant Just pushed a test version to the branch DefaultVolume. Do you know how to test this through git? I'm interested in if you agree with how this works?
The issue is that you can't set the volume directly after changing the input. I added a delay of 2 sec after changing the input. In my case this is around the same time it takes to change the input so you don't notice the delay.
