### ISSUE TITLE
Homebridge 0.6.0 beta - failed to register plugin

### ISSUE THREAD

**Issue by ChrWi** [Martvvliet/homebridge-denon-heos#29]
When contributing to homebridge 0.6.0 beta test - see https://github.com/homebridge/homebridge/issues/2459# - your plugin failed to register :“plugin incorrectly registered an external accessory using the platform name (homebridge-denon-heos) and not the plugin identifier. please report to the developer!

It works on 0.4.53 with latest 2.4.0. Can you please crosscheck? Thanks!

**Comment by Supereg** [comment]
Okay. This is weird while the plugin indeed registers correctly with the plugin identifier. Are you running the latest beta?

**Comment by Supereg** [comment]
https://github.com/Martvvliet/homebridge-denon-heos/blob/68b5544a6a3e2004b0a2bf0023ce91b7c0493282/index.js#L8

Is see. You got a typo in your plugin name. Would currently suggest that you keep the misspelled name if you are using a dynamic platform plugin. Otherwise Homebridge wouldn't be able to link accessories stored to disk back to the plugin.

**Comment by Martvvliet** [comment]
@ChrWi Thank for notifying. @Supereg yeah, stupid mistake :/ I will probably update this with the next release. This will also include the homebridge GUI. Thanks for finding it out :)

**Comment by Martvvliet** [comment]
Type is fixed in new version. Thank you both for informing me :)
