### ISSUE TITLE
Zone2 support

### ISSUE THREAD

**Issue by rbswift** [Martvvliet/homebridge-denon-heos#39]
I was looking at multi-zone support. I see that multiple platforms are already supported.

Would it be possible to tweak multi-platform support so that each platform can be configured with a URL? The default URL could be "formMainZone_MainZoneXmlStatusLite.xml" and this could be manually changed to "formMainZone_MainZoneXmlStatusLite.xml?_=&ZoneName=ZONE2" by anyone wanting a second zone?

If this doesn't work then maybe this issue can be a placeholder for someone to come up with something that does :)

**Comment by Martvvliet** [comment]
I have several requests already on the multi zone support, so I will add this in the near future. Thank you for your interest :)

**Comment by Martvvliet** [comment]
In version 2.6.0 zone2 and 3 support is added. Can you let me know if everything is working as is should be?

**Comment by rbswift** [comment]
Thanks for this. I've tested the volume control with 2 zones and managed to get it working. There seems to be a slight problem with switching on the zone (light). In my setup the volume changes but the zone does not switch on. Instead, when I attempt to switch it on, the Home app briefly shows the zone/light as switched on for a couple of seconds and then changes back to showing switched off status. I'm not sure how this worked before so it may not be a new multizone problem . I will try to test the other sections too

**Comment by rinoronie** [comment]
I try the 2.6.0 version, but the switch from source not works.
I rollback to 2.5.4

**Comment by rbswift** [comment]
Both main zone and zone2 TV accessories seem to work fine for me so far. Thanks.

**Comment by Martvvliet** [comment]
@rinoronie indeed, I noticed this. It is fixed in version 2.6.2. Thank you for input. 
@rbswift The power state of a lightbulb is standing for the mute state of the receiver. So it should not turn on when setting the volume bulb. The best thing to do is to add the receiver zone 2 as a switch or as a tv service. This way you can control the power state of zone 2 and turn on/off the mute state.
Besides that thank you for testing if everything is working :)
