### ISSUE TITLE
Request for changing types

### ISSUE THREAD

**Issue by seanzhang98** [Martvvliet/homebridge-denon-heos#51]
I believe that there are support for audio receiver in iOS 13 and 14, is it possible to add receiver as audio receiver instead of TV?

**Comment by seanzhang98** [comment]
<img width="114" alt="截屏2020-07-08 下午2 17 51" src="https://user-images.githubusercontent.com/34902361/86884281-ef3e2700-c125-11ea-84b4-b0ca44b0b0f1.png">
This is show in iOS 14 Beta 1

**Comment by Martvvliet** [comment]
The API supports receivers, but the Home app doesn't. Same holds for speakers for the absolute volume control. When I use a speaker instead of a lightbulb, it is not recognised anymore in the Home app, but Home+ does support this for example. Looks like iOS 14 will support receivers though. It is removed in Beta 2 but will I hope Beta 3 will add it again. It should automatically change to a receiver if it is supported again.

**Comment by Martvvliet** [comment]
Since IOS 14, this is readded again gladly. Maybe you will have to re-add it to the home app (is what I had to do), but it is finally shown as a receiver now. The volume control is sadly not yet supported as a speaker in the Home app.

**Comment by seanzhang98** [comment]
Thank you! I will try it once I get home.> Since IOS 14, this is readded again gladly. Maybe you will have to re-add it to the home app (is what I had to do), but it is finally shown as a receiver now. The volume control is sadly not yet supported as a speaker in the Home app.
